export const BOOKED_CREATE_REQUEST = "BOOKED_CREATE_REQUEST";
export const BOOKED_CREATE_SUCCESS = "BOOKED_CREATE_SUCCESS";
export const BOOKED_CREATE_FAIL = "BOOKED_CREATE_FAIL";

export const BOOKED_DETAILS_REQUEST = "BOOKED_DETAILS_REQUEST";
export const BOOKED_DETAILS_SUCCESS = "BOOKED_DETAILS_SUCCESS";
export const BOOKED_DETAILS_FAIL = "BOOKED_DETAILS_FAIL";

export const BOOKED_MY_ORDER_REQUEST = "BOOKED_MY_ORDER_REQUEST";
export const BOOKED_MY_ORDER_SUCCESS = "BOOKED_MY_ORDER_SUCCESS";
export const BOOKED_MY_ORDER_FAIL = "BOOKED_MY_ORDER_FAIL";
export const BOOKED_MY_ORDER_RESET = "BOOKED_MY_ORDER_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_CONFIRM_REQUEST = "ORDER_CONFIRM_REQUEST";
export const ORDER_CONFIRM_SUCCESS = "ORDER_CONFIRM_SUCCESS";
export const ORDER_CONFIRM_FAIL = "ORDER_CONFIRM_FAIL";
export const ORDER_CONFIRM_RESET = "ORDER_CONFIRM_RESET";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";
