export const COUNSELLOR_LIST_REQUEST = "COUNSELLOR_LIST_REQUEST";
export const COUNSELLOR_LIST_SUCCESS = "COUNSELLOR_LIST_SUCCESS";
export const COUNSELLOR_LIST_FAILURE = "COUNSELLOR_LIST_FAILURE";

export const COUNSELLOR_DETAILS_REQUEST = "COUNSELLOR_DETAILS_REQUEST";
export const COUNSELLOR_DETAILS_SUCCESS = "COUNSELLOR_DETAILS_SUCCESS";
export const COUNSELLOR_DETAILS_FAILURE = "COUNSELLOR_DETAILS_FAILURE";

export const COUNSELLOR_DELETE_REQUEST = "COUNSELLOR_DELETE_REQUEST";
export const COUNSELLOR_DELETE_SUCCESS = "COUNSELLOR_DELETE_SUCCESS";
export const COUNSELLOR_DELETE_FAIL = "COUNSELLOR_DELETE_FAILURE";

export const COUNSELLOR_CREATE_REQUEST = "COUNSELLOR_CREATE_REQUEST";
export const COUNSELLOR_CREATE_SUCCESS = "COUNSELLOR_CREATE_SUCCESS";
export const COUNSELLOR_CREATE_FAIL = "COUNSELLOR_CREATE_FAILURE";
export const COUNSELLOR_CREATE_RESET = "COUNSELLOR_CREATE_RESET";

export const COUNSELLOR_UPDATE_REQUEST = "COUNSELLOR_UPDATE_REQUEST";
export const COUNSELLOR_UPDATE_SUCCESS = "COUNSELLOR_UPDATE_SUCCESS";
export const COUNSELLOR_UPDATE_FAIL = "COUNSELLOR_UPDATE_FAILURE";
export const COUNSELLOR_UPDATE_RESET = "COUNSELLOR_UPDATE_RESET";
